apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.runtime }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.runtime }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}

